# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('scene1', models.CharField(max_length=20)),
                ('scene2', models.CharField(max_length=20)),
                ('station', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('visited_times', models.IntegerField()),
                ('last_visit_date', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
