# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160807_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='last_visit_date',
            field=models.DateField(null=True),
        ),
    ]
